### ISSUE TITLE
What am I missing to run RingVideos?

### ISSUE THREAD

**Issue by LyNac** [mmckechney/RingVideos#11]
I'm using Ubuntu 18.04 and when I run wine RingVideos --version (or any parameter, really), I get this result:

002c:fixme:msvcrt:_configure_wide_argv (1) stub
002c:fixme:msvcrt:_initialize_wide_environment stub
002c:fixme:heap:GetNumaHighestNodeNumber semi-stub: 00000000002AEBA8
002c:fixme:ntdll:EtwEventRegister ({e13c0d23-ccbc-4e12-931b-d9cc2eee27e4}, 0x8b69b0, 0xbaa720, 0xbaa720) stub.
002c:fixme:ntdll:EtwEventRegister ({763fd754-7086-4dfe-95eb-c01a46faf4ca}, 0x8b69b0, 0xbaa680, 0xbaa680) stub.
002c:fixme:ntdll:EtwEventRegister ({a669021c-c450-4609-a035-5af59af4df18}, 0x8b69b0, 0xbaa6d0, 0xbaa6d0) stub.
002c:fixme:wer:WerRegisterRuntimeExceptionModule (L"Z:\\home\\lynda\\Downloads\\RingVideos\\mscordaccore.dll", 0x690000) stub!
002c:fixme:ntdll:NtQuerySystemInformation info_class SYSTEM_PERFORMANCE_INFORMATION
002c:fixme:ntdll:EtwEventRegister ({49592c0f-5a05-516d-aa4b-a64e02026c89}, 0xc43044, (nil), 0x10a8ff8) stub.
002c:fixme:ntdll:EtwEventRegister ({5e5bb766-bbfc-5662-0548-1d44fad9bb56}, 0xc43084, (nil), 0x10a9308) stub.
002c:fixme:ntdll:EtwEventSetInformation (deadbeef, 2, 0x10a92b0, 34) stub
002c:fixme:ntdll:EtwEventSetInformation (deadbeef, 2, 0x10a8e60, 17) stub
002c:fixme:nls:CompareStringEx semi-stub behavior for flag(s) 0x8000000
0033:fixme:sync:SetWaitableTimerEx (0000000000000180, 000000001A67FD38, 500, 0000000000000000, 0000000000000000, 0000000000000000, 50) semi-stub
002c:fixme:ntdll:EtwEventRegister ({2e5dba47-a3d2-4d16-8ee0-6671ffdcd7b5}, 0xc43144, (nil), 0x10bff58) stub.
002c:fixme:ntdll:EtwEventSetInformation (deadbeef, 2, 0x10bff00, 40) stub
002c:fixme:ntdll:EtwEventRegister ({0866b2b8-5cef-5db9-2612-0c0ffd814a44}, 0xc431c4, (nil), 0x10c0fb8) stub.
002c:fixme:ntdll:EtwEventSetInformation (deadbeef, 2, 0x10c0f60, 38) stub
002c:fixme:ntdll:EtwEventRegister ({27837f46-1a43-573d-d30c-276de7d02192}, 0xc43244, (nil), 0x10d2bc0) stub.
002c:fixme:ntdll:EtwEventSetInformation (deadbeef, 2, 0x10d2b60, 43) stub
002c:err:winediag:SECUR32_initNTLMSP ntlm_auth was not found or is outdated. Make sure that ntlm_auth >= 3.0.25 is in your path. Usually, you can find it in the winbind package of your distribution.
002c:fixme:ntdll:NtQuerySystemInformation (0x000000ce,0x2ac198,0x00000008,(nil)) stub
002c:fixme:nls:GetFileMUIPath stub: 0x10, L"C:\\windows\\system32\\tzres.dll", (null), 0x2acfa0, 0x2acd50, 0x2acfa8, 0x2acf98
002c:fixme:nls:GetFileMUIPath stub: 0x10, L"C:\\windows\\system32\\tzres.dll", (null), 0x2acfa0, 0x2acd50, 0x2acfa8, 0x2acf98
Required command was not provided.

RingVideos:
  Simple command line tool to download videos from your Ring account

Usage:
  RingVideos [options] [command]

Options:
  --version         Show version information
  -?, -h, --help    Show help and usage information

Commands:
  starred     Download only starred videos
  all         Download all videos (starred and unstarred)
  snapshot    Download only snapshot images

0036:fixme:nls:get_dummy_preferred_ui_language (0x8 0x1b4aeea0 (nil) 0x1b4aee98) returning a dummy value (current locale)
0036:fixme:nls:get_dummy_preferred_ui_language (0x8 0x1b4aeea0 0x10d9008 0x1b4aee98) returning a dummy value (current locale)
0035:fixme:ntdll:EtwEventRegister ({8e9f5090-2d75-4d03-8a81-e5afbf85daf1}, 0xc432c4, (nil), 0x1140e18) stub.
0035:fixme:ntdll:EtwEventRegister ({35167f8e-49b2-4b96-ab86-435b59336b5e}, 0xc43344, (nil), 0x1141c68) stub.
0035:fixme:ntdll:EtwEventSetInformation (deadbeef, 2, 0x1141bf0, 65) stub
002e:fixme:ntdll:EtwEventUnregister (deadbeef) stub.
002e:fixme:ntdll:EtwEventUnregister (deadbeef) stub.
002e:fixme:ntdll:EtwEventUnregister (deadbeef) stub.
002e:fixme:ntdll:EtwEventUnregister (deadbeef) stub.
002e:fixme:ntdll:EtwEventUnregister (deadbeef) stub.
002e:fixme:ntdll:EtwEventUnregister (deadbeef) stub.
002e:fixme:ntdll:EtwEventUnregister (deadbeef) stub.

**Comment by mmckechney** [comment]
That's a new one! Can you tell me what OS you are running, and can you verify that your system is patched and up to date? 
It looks like you might be running in a Wine emulator? If that is the case, you can compile this to compile natively for Linux or Mac instead. 
If you don't have the ability to do so, I can make a build and post it, but will need to know OS and version number.

**Comment by mmckechney** [comment]
Actually -- already created a Linux build.. 
Try downloading the "ringvideos-linux" artifact from this build: https://github.com/mmckechney/RingVideos/actions/runs/615755130 and let me know if that works for you. If it does, I will start adding an official "release" for Linux next time I make an update.

**Comment by LyNac** [comment]
Thanks! I am attempting to run it in a Wine emulator through Ubuntu 18.04.

I received a different error this time, when I entered `wine RingVideos --version`

0009:err:module:__wine_process_init L"C:\\windows\\system32\\RingVideos.exe" not found

If I don't run it through Wine, it just says "RingVideos.exe: command not found."

**Comment by mmckechney** [comment]
The Linux compiled version won't  need the emulator, it will run native on Ubuntu. Try that instead. I don't have any experience with Wine, but was able to run it successfully straight on Linux

**Comment by LyNac** [comment]
Even after marking it as executable with `chmod -x RingVideos`, it still returns "RingVideos: command not found."

**Comment by mmckechney** [comment]
Try running it as `./RingVideos` (with the dot slash ./) Your bash window probably requires this to run an  executable

**Comment by LyNac** [comment]
That did it! Thanks so much for all the help and this awesome app. I'm running into errors with the --start and --end options, everything works perfectly except when I try to specify a start and end date/time I get the error:

Unrecognized command or argument '12:00:00'
Unrecognized command or argument 'AM'
Unrecognized command or argument '11:59:59'
Unrecognized command or argument 'PM'

**Comment by mmckechney** [comment]
Sorry for the delay in getting back to you... for some reason, I don't get updates on this.
Anyway, I have just pushed an update that will (hopefully) solve your problem. You can download and try the latest version (2.0.2) here: https://github.com/mmckechney/RingVideos/releases/tag/2.0.2

**Comment by LyNac** [comment]
No problem, I appreciate you addressing the file handling issue and the end date issue!

I remembered to make RingVideos executable and once I did that it works great, no fail messages so far! Thank you, you're a hero!
